name: Cypress e2e checks
on:
  pull_request:
    types: [ labeled ]

jobs:
  post:
    name: Posting to twitter
    if: ${{ github.event.label.name == 'post-twitter' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Post tip of the day
        run: sh ./scripts/post-twitter.sh
        env:
          VIM_TIPS_API_SECRET: ${{ secrets.VIM_TIPS_API_SECRET }}
