on: push
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17.4'
          cache: 'yarn'
      - name: Setup
        run: yarn
      - name: Building
        run: yarn build
      - name: Testing
        run: yarn jest
