on:
  workflow_dispatch:
  schedule:
    # Post a new tip every day at 8:30
    - cron: "30 8 * * *"

jobs:
  post_tip:
    name: Posting to twitter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "17.4"
          cache: "yarn"
      - name: Setup
        run: yarn
      - name: Post tip of the day
        run: sh ./scripts/post-twitter.sh
        env:
          SERVICE_API_URL: ${{ secrets.SERVICE_API_URL }}
          VIM_TIPS_API_SECRET: ${{ secrets.VIM_TIPS_API_SECRET }}
